---
title: Shasthojoy.Cloud-Services
timezone: Asia/Dhaka
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
name: Shasthojoy
description: Cloud based healthcare management services for developing world hospitals.
url: http://shasthojoy.com
permalink: "/blog/:year/:month/:title"
exclude:
- script
- vendor
- Gemfile
- Gemfile.lock
- config.ru
- Procfile
- Rakefile
- readme.md
sass: 
sass_dir: _sass
